# Generated by Django 5.0.4 on 2024-05-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_rangers_api", "0001_restart_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitstation",
            name="mode",
            field=models.IntegerField(
                choices=[
                    (0, "Tram, Streetcar, Light rail."),
                    (1, "Subway, Metro"),
                    (2, "Rail"),
                    (3, "Bus"),
                    (4, "Ferry"),
                    (5, "Cable car"),
                    (6, " Aerial lift, suspended cable car"),
                    (7, "Funicular"),
                    (11, "Trolleybus"),
                    (12, "Monorail"),
                ],
                default=1,
                verbose_name="Mode of transportation",
            ),
            preserve_default=False,
        ),
    ]
