# Generated by Django 5.0.4 on 2024-05-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_rangers_api", "0003_alter_bikestation_station_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikestation",
            name="station_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="bikestation",
            name="station_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="census_block",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="county",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="disability_status",
            field=models.IntegerField(
                null=True, verbose_name="Number of people with disability"
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="state",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="vehicles_available",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="transitroute",
            name="route_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="transitroute",
            name="route_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="transitstation",
            name="station_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="transitstation",
            name="station_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="bikeridership",
            constraint=models.UniqueConstraint(
                fields=("station_id", "date"), name="bike_ridership"
            ),
        ),
        migrations.AddConstraint(
            model_name="ridershiproute",
            constraint=models.UniqueConstraint(
                fields=("route_id", "date"), name="route_ridership"
            ),
        ),
        migrations.AddConstraint(
            model_name="ridershipstation",
            constraint=models.UniqueConstraint(
                fields=("station_id", "date"), name="station_ridership"
            ),
        ),
    ]
