# Generated by Django 5.0.4 on 2024-05-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "route_rangers_api",
            "0005_rename_census_block_demographics_block_group_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="demographics",
            name="population",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="stationrouterelation",
            constraint=models.UniqueConstraint(
                fields=("station", "route"), name="station_route"
            ),
        ),
    ]
