# Generated by Django 5.0.4 on 2024-05-14 20:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_rangers_api", "0006_demographics_population_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="demographics",
            name="demographic_uniqueness",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="block_group",
        ),
        migrations.AddField(
            model_name="demographics",
            name="geographic_delimitation",
            field=django.contrib.gis.db.models.fields.PolygonField(
                null=True, srid=4326
            ),
        ),
        migrations.AddConstraint(
            model_name="demographics",
            constraint=models.UniqueConstraint(
                fields=("census_tract", "county", "state"),
                name="demographic_uniqueness",
            ),
        ),
    ]
