# Generated by Django 5.0.4 on 2024-05-18 23:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "route_rangers_api",
            "0008_remove_survey_id_remove_survey_questionnaire_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("route_id", models.CharField(max_length=128)),
                (
                    "response_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Survey response date"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("CHI", "Chicago"),
                            ("NYC", "New York"),
                            ("PDX", "Portland"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "route",
                    django.contrib.gis.db.models.fields.LineStringField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "starting_point",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "end_point",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "trip_frequency",
                    models.IntegerField(
                        choices=[
                            (1, "Everyday"),
                            (2, "Weekdays"),
                            (3, "Weekends"),
                            (4, "A few times per week"),
                            (5, "A few times per month"),
                            (6, "A few times per year"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "trip_tod",
                    models.IntegerField(
                        choices=[
                            (1, "Peak commute hours"),
                            (2, "Daytime"),
                            (3, "Nighttime"),
                        ],
                        null=True,
                    ),
                ),
                ("trip_time", models.IntegerField(null=True)),
                (
                    "modes_of_transit",
                    models.IntegerField(
                        choices=[
                            (1, "Bus"),
                            (2, "Train"),
                            (3, "Car"),
                            (4, "Bike"),
                            (5, "Walking"),
                            (6, "Rideshare"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "satisfied",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "transit_improvement",
                    models.IntegerField(
                        choices=[
                            (1, "More frequent service"),
                            (2, "More accurate schedule times"),
                            (3, "Fewer transfers or a more direct route"),
                            (4, "It feels safe at the station and onboard"),
                            (5, "No improvement needed"),
                        ],
                        null=True,
                    ),
                ),
                ("transit_improvement_open", models.CharField(max_length=128)),
                (
                    "switch_to_transit",
                    models.IntegerField(
                        choices=[
                            (1, "There are stops near you"),
                            (2, "There are many scheduled departures"),
                            (3, "It doesn't take significantly longer than driving"),
                            (4, "There are enough seats for all riders"),
                            (5, "It feels safe at the station and onboard"),
                            (6, "It will save me money"),
                            (7, "I would not be willing to switch to transit"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyUser",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("CHI", "Chicago"),
                            ("NYC", "New York"),
                            ("PDX", "Portland"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "frequent_transit",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], null=True),
                ),
                (
                    "car_owner",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], null=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
        migrations.DeleteModel(
            name="SurveyAnswer",
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="route_rangers_api.surveyuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.UniqueConstraint(
                fields=("user_id", "route_id"), name="survey_route"
            ),
        ),
    ]
