# Generated by Django 5.0.4 on 2024-05-22 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_rangers_api", "0009_changing_survey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresponse",
            name="transit_improvement_open",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="trip_time",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(240),
                ],
            ),
        ),
    ]
